"""Recriando tabelas para avaliação

Revision ID: 5e5521756ab2
Revises: bf333da851f9
Create Date: 2025-01-16 23:17:43.822040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5521756ab2'
down_revision = 'bf333da851f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semestres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_semestre', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_semestre')
    )
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_disciplina', sa.String(length=64), nullable=True),
    sa.Column('semestre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['semestre_id'], ['semestres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disciplinas_name_disciplina'), ['name_disciplina'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disciplinas_name_disciplina'))

    op.drop_table('disciplinas')
    op.drop_table('semestres')
    # ### end Alembic commands ###
