"""Recriando tabelas para avaliação

Revision ID: bf333da851f9
Revises: 89a148851cb6
Create Date: 2025-01-16 22:43:24.081781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf333da851f9'
down_revision = '89a148851cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semestres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_semestre', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_semestre')
    )
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_disciplina', sa.String(length=64), nullable=True),
    sa.Column('semestre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['semestre_id'], ['semestres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disciplinas_name_disciplina'), ['name_disciplina'], unique=True)

    op.drop_table('roles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username')

    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_username', ['username'], unique=1)

    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disciplinas_name_disciplina'))

    op.drop_table('disciplinas')
    op.drop_table('semestres')
    # ### end Alembic commands ###
